Rebased History (FIRST COMMIT) - these changes make AdvancedTomato Interface tick

diff --git a/release/src-rt-6.x.4708/router/www/Makefile b/release/src-rt-6.x.4708/router/www/Makefile
--- a/release/src-rt-6.x.4708/router/www/Makefile
+++ b/release/src-rt-6.x.4708/router/www/Makefile
@@ -6,36 +6,48 @@ all:
 clean:
 
 install:
+# Create initial folders
 	rm -rf $(INSTALLDIR)/www
-	mkdir -p $(INSTALLDIR)/www
+	mkdir -p $(INSTALLDIR)/www			
+	mkdir -p $(INSTALLDIR)/www/js
+	mkdir -p $(INSTALLDIR)/www/css
 
-	cp *.gif *.png *.ico *.html *.php robots.txt $(INSTALLDIR)/www
+# Copy files we don't want to modify to new install directory
+	cp *.ico *.html *.php robots.txt $(INSTALLDIR)/www
 
-# squish some of the files by trimming whitespace...
-
-	for F in $(wildcard *.js *.jsx); do \
+# Copy JS files to the installdir and squish files by trimming whitespace
+	for F in $(wildcard js/*.js js/*.jsx *.js *.jsx); do \
 		sed '/^\/\*\s*$$/,/\*\//! { s/^\s\+//; s/\s\+$$//; /^\/\/ --\+\s*/d; /^$$/d }' < $$F > $(INSTALLDIR)/www/$$F; \
 	done
 
-	for F in $(wildcard *.css); do \
+# Copy CSS files to the installdir and squish files by trimming whitespace
+	for F in $(wildcard css/*.css *.css); do \
 		sed '/^\/\*\s*$$/,/\*\//! { s/\s\+/ /g; s/^\s\+//; s/\s\+$$//; /^$$/d }' < $$F > $(INSTALLDIR)/www/$$F; \
 	done
 
+# Copy asp files to the installdir	
 # remove "debug.js" references, convert color.css, remove comments
 # in between REMOVE-BEGIN and REMOVE-END, and compress whitespace
+# (and copy them to the INSTALLDIR)
+#
+# The expressions to delete comments from asp files are placed further down the Makefile, to affect not only these
+# asp files
+# 			-e "s,<!-- / / / -->,," \
+#			-e "/^<!--$$/,/^-->$$/! { s,^\s\+, , }" 
+#
 
 	for F in $(wildcard *.asp *.svg); do \
 		sed	-e "/REMOVE-BEGIN/,/REMOVE-END/d" \
 			-e "s,<script[^>]\+debug\.js[^>]\+></script>,," \
 			-e "s,<link[^>]\+href='color\.css'>,<% css(); %>," \
 			-e "s,color\.css,<% nv('web_css'); %>\.css," \
-			-e "s,<!-- / / / -->,," \
 			-e "s,\x0d,," \
 			-e "s,^\s\+,," \
 			-e "/^$$/d" \
-			-e "/^<!--$$/,/^-->$$/! { s,^\s\+, , }" $$F > $(INSTALLDIR)/www/$$F; \
+			$$F > $(INSTALLDIR)/www/$$F; \
 	done
 
+#-------------------------------- COMPILER DIRECTIVES -----------------------------------------------
 # Only include Linux 2.6 options if building for Linux 2.6.
 ifneq ($(CONFIG_LINUX26),y)
 	cd $(INSTALLDIR)/www && \
@@ -132,7 +144,7 @@ endif
 # Victek for RAF verion
 # Only include Captive Portal menu option and pages when configured.
 ifneq ($(TCONFIG_NOCAT),y)
-	rm -f $(INSTALLDIR)/www/splashd.asp
+	rm -f $(INSTALLDIR)/www/advanced-splashd.asp
 	rm -f $(INSTALLDIR)/www/splash.html
 	rm -f $(INSTALLDIR)/www/style.css
 	sed -i $(INSTALLDIR)/www/tomato.js -e "/NOCAT-BEGIN/,/NOCAT-END/d"
@@ -149,7 +161,6 @@ ifneq ($(TCONFIG_NGINX),y)
 	sed -i $(INSTALLDIR)/www/tomato.js -e "/NGINX-BEGIN/,/NGINX-END/d"
 	sed -i $(INSTALLDIR)/www/about.asp -e "/NGINX-BEGIN/,/NGINX-END/d"
 endif
-
 
 # Only include HFS/HFS+ option and pages when configured.
 ifneq ($(TCONFIG_HFS),y)
@@ -247,7 +258,7 @@ ifeq ($(TCONFIG_OPENVPN),y)
 else
 	rm -f $(INSTALLDIR)/www/vpn-server.asp
 	rm -f $(INSTALLDIR)/www/vpn-client.asp
-	rm -f $(INSTALLDIR)/www/vpn.js
+	rm -f $(INSTALLDIR)/www/js/vpn.js
 	sed -i $(INSTALLDIR)/www/tomato.js -e "/ OPENVPN-BEGIN/,/ OPENVPN-END/d"
 	sed -i $(INSTALLDIR)/www/about.asp -e "/ OPENVPN-BEGIN/,/ OPENVPN-END/d"
 endif
@@ -305,9 +316,17 @@ ifeq ($(TCONFIG_DNSCRYPT),y)
 else
 	sed -i $(INSTALLDIR)/www/basic-network.asp -e "/DNSCRYPT-BEGIN/,/DNSCRYPT-END/d"
 	sed -i $(INSTALLDIR)/www/about.asp -e "/DNSCRYPT-BEGIN/,/DNSCRYPT-END/d"
-endif
+ endif
 
-# clean up
+#-------------------------------- END COMPILER DIRECTIVES -----------------------------------------------
+# Copy over the directories required for AdvancedTomato GUI (img and fonts), functions affect these files too
+	mkdir -p $(INSTALLDIR)/www/img
+	cp -r img/* $(INSTALLDIR)/www/img/.
+
+	mkdir -p $(INSTALLDIR)/www/css/fonts
+	cp -r css/fonts/* $(INSTALLDIR)/www/css/fonts/.
+	
+# clean up compiler directives
 	cd $(INSTALLDIR)/www && \
 	for F in $(wildcard *.asp *.js *.jsx *.html); do \
 		[ -f $(INSTALLDIR)/www/$$F ] && sed -i $$F \
@@ -349,15 +368,51 @@ endif
 		|| true; \
 	done
 
+# After cleaning up the compiler directive, all html comments in asp can be removed
+	cd $(INSTALLDIR)/www && \
+	for F in $(wildcard *.asp *.html); do \
+		[ -f $(INSTALLDIR)/www/$$F ] && sed -i $$F \
+		-e :a -re 's/<!--.*?-->//g;/<!--/N;//ba' \
+		|| true; \
+	done
+	
+# Remove all javascript multiline comments in asp files
+	cd $(INSTALLDIR)/www && \
+	for F in $(wildcard *.asp *.html); do \
+		[ -f $(INSTALLDIR)/www/$$F ] && sed -i $$F \
+		-e :a -re 's%(.*)/\*.*\*/%\1%; ta; /\/\*/ !b; N; ba' \
+		|| true; \
+	done
+
+# Copy YUI Compressor into WWW directory
+	cp tools/yuicompressor-2.4.8.jar $(INSTALLDIR)/www
+		
+# Compress JAVASCRIPT files
+	cd $(INSTALLDIR)/www && \
+	for F in $(wildcard js/*.js *.js ); do \
+		[ -f $(INSTALLDIR)/www/$$F ] && java -jar yuicompressor-2.4.8.jar --type js -v -o $$F $$F || true; \
+	done 
+
+# Compress CSS files
+	cd $(INSTALLDIR)/www && \
+	for F in $(wildcard css/*.css *.css ); do \
+			[ -f $(INSTALLDIR)/www/$$F ] && java -jar yuicompressor-2.4.8.jar --type css -v -o $$F $$F || true; \
+	done 
+
+# Remove yuicompressor
+	rm 	$(INSTALLDIR)/www/yuicompressor-2.4.8.jar
+
 # make sure old and debugging crap is gone
 	@rm -f $(INSTALLDIR)/www/debug.js
 	@rm -f $(INSTALLDIR)/www/*-x.*
 	@rm -f $(INSTALLDIR)/www/*-old.*
 	@rm -f $(INSTALLDIR)/www/color.css
 
-	chmod 0644 $(INSTALLDIR)/www/*
+# secure the files in the installdir and change file ACLs (and preserve the existing folder ACLs)
+#	chmod 0644 $(INSTALLDIR)/www/*
+	find $(INSTALLDIR)/www/ -type f -print0 | xargs -0 chmod 644	
 
 # remove C-style comments from java files. All "control" comments have been processed by now.
-	for F in $(wildcard *.js *.jsx); do \
+	for F in $(wildcard js/*.jsx *.jsx); do \
 		[ -f $(INSTALLDIR)/www/$$F ] && $(TOP)/www/remcoms2.sh $(INSTALLDIR)/www/$$F c; \
 	done
